import image from "@/public/ImageHero.png";

export const machines = [
    {
    id: 1,
    serviceId: "location",
    title: "AeroCrop Gen 4",
    slug: "aerocrop-gen-4",
    category: "Drone",
    badge: "Location",
    image: image,
    price: "sur  devis",
    featured: true,
  },
  {
    id: 2,
    serviceId: "location",
    title: "Titan X-800",
    slug: "Titan-X-800",
    category: "Moissonneuse-batteuse",
    badge: "Nouveau",
    image: image,
    price: "Sur devis",
    featured: true,
  },
  {
    id: 3,
    serviceId: "location",
    title: "John Deere 8R 410",
    slug: "John-Deere-8R-410",
    category: "Tracteur forte puissance",
    badge: "",
    image: image,
    price: "Sur devis",
    featured: true,
  },
  {
    id:4,
    serviceId: "location",
    title: "Orchard Pro 250",
    slug: "Orchard-Pro-250",
    category: "Récolteuse de fruits",
    badge: "Occasion Or",
    image: image,
    price: "Sur devis",
    featured: true,
  },
  {
    id:5,
    serviceId: "outils-agricoles",
    title: "AeroCrop Gen 4",
    slug: "AeroCrop-Gen-4",
    category: "Drone de précision",
    badge: "Location",
    image: image,
    price: "Sur devis",
    featured: true,
  },
  {
    id:6,
    serviceId: "vente-tracteurs",
    title: "Deere-8R-410-John",
    slug: "Deere-8R-410-John ",
    category: "Drone de précision",
    badge: "Location",
    image: image,
    price: "Sur devis",
    featured: true,
  },
  {
    id:7,
    serviceId: "outils-agricoles",
    title: "Gen AeroCrop 4",
    slug: "Gen-AeroCrop-4",
    category: "Drone de précision",
    badge: "Location",
    image: image,
    price: "Sur devis",
    featured: true,
  },
];