import image from "@/public/ImageHero.png";


export const machines = [
  {
    id: 1,
    serviceId: "location",
    title: "AeroCrop Gen 4",
    slug: "aerocrop-gen-4",
    category: "Drone",
    badge: "Location",
    brand: "John Deere",
    image: image,
    price: 85.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,

    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id: 2,
    serviceId: "location",
    title: "Titan X-800",
    slug: "Titan-X-800",
    category: "Moissonneuse",
    badge: "Nouveau",
    brand: "John Deere",
    image: image,
    price: 18.00,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,

    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: false,
  },
  {
    id: 3,
    serviceId: "location",
    title: "John Deere 8R 410",
    slug: "John-Deere-8R-410",
    category: "Tracteur puissance",
    badge: "",
    brand: "John Deere",
    image: image,
    price: 38.500,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,

    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id:4,
    serviceId: "location",
    title: "Orchard Pro 250",
    slug: "Orchard-Pro-250",
    category: "Recolte fruits",
    badge: "Occasion Or",
    brand: "New Holland",
    image: image,
    price: 385.000,
    power: 410,
    hours: 1240,
    transmission: "e23",
    year: 2023,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: false,
  },
  {
    id:5,
    serviceId: "outils-agricoles",
    title: "AeroCrop Gen 4",
    slug: "AeroCrop-Gen-4",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 58.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,

    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id:6,
    serviceId: "vente-tracteurs",
    title: "Deere 8R 410 John",
    slug: "Deere-8R-John ",
    category: "Drone précision",
    badge: "Location",
    brand: "New Holland",
    image: image,
    price: 5.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,

    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: false,
  },
  {
    id:7,
    serviceId: "outils-agricoles",
    title: "Gen AeroCrop 4",
    slug: "Gen-AeroCrop-4",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 15.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id:8,
    serviceId: "outils-agricoles",
    title: "Gen 8 AeroCrop",
    slug: "Gen-8-AeroCrop",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 15.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: false,
  },
  {
    id:9,
    serviceId: "outils-agricoles",
    title: "AeroCrop 5 Gen",
    slug: "AeroCrop-5-Gen",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 15.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id:10,
    serviceId: "outils-agricoles",
    title: "10 Gen AeroCrop",
    slug: "10-Gen-AeroCrop",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 15.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id:11,
    serviceId: "outils-agricoles",
    title: "Gen AeroCrop 11",
    slug: "Gen-AeroCrop-11",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 15.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
  {
    id:12,
    serviceId: "outils-agricoles",
    title: "Gen 12 AeroCrop",
    slug: "Gen-12-AeroCrop",
    category: "Drone précision",
    badge: "Location",
    brand: "Case IH",
    image: image,
    price: 15.000,
    power: 410,
    hours: 1240,
    description:
          "Semence de soja sélectionnée pour améliorer le rendement.",
    transmission: "e23",
    year: 2023,
    engine: "John Deere PowerTech™ PSS 9,0 L",
    cylinders: 6,
    fuelCapacity: 727,
    hydraulicFlow: 227,
    shippingWeight: 14000,
    equipment: [
      {
        label: "Guidage AutoTrac™",
        icon: "Satellite",
      },
      {
        label: "Climatisation Auto",
        icon: "Snowflake",
      },
      {
        label: "Pack éclairage LED",
        icon: "Lightbulb",
      },
      {
        label: "Siège ActiveSeat™ II",
        icon: "UserRound",
      },
      {
        label: "JDLink™ télématique",
        icon: "Radio",
      },
      {
        label: "Radar de vitesse",
        icon: "Gauge",
      },
    ],
    featured: true,
  },
];